name: Input Event Workflow

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose an action'
        required: true
        default: 'build'
        # Define the available options as a comma-separated string
        options: 'build, test, deploy'

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Perform chosen action
        run: |
          if [ "${{ github.event.inputs.action }}" = "build" ]; then
            # Perform build steps
            echo "Building..."
          elif [ "${{ github.event.inputs.action }}" = "test" ]; then
            # Perform test steps
            echo "Testing..."
          elif [ "${{ github.event.inputs.action }}" = "deploy" ]; then
            # Perform deployment steps
            echo "Deploying..."
          else
            echo "Invalid action specified"
            exit 1
          fi
